// Date: 6/25/2014 8:50:05 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package com.labswag.seamusfd.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelScientificGrinder extends ModelBase
{
    //fields
    ModelRenderer ScientificGrinderBase;
    ModelRenderer TopBase;
    ModelRenderer TopPole;

    public ModelScientificGrinder()
    {
        textureWidth = 64;
        textureHeight = 32;

        ScientificGrinderBase = new ModelRenderer(this, 0, 0);
        ScientificGrinderBase.addBox(-6F, 0F, -6F, 12, 10, 12);
        ScientificGrinderBase.setRotationPoint(0F, 14F, 0F);
        ScientificGrinderBase.setTextureSize(64, 32);
        ScientificGrinderBase.mirror = true;
        setRotation(ScientificGrinderBase, 0F, 0F, 0F);
        TopBase = new ModelRenderer(this, 0, 22);
        TopBase.addBox(0F, 0F, 0F, 8, 1, 8);
        TopBase.setRotationPoint(-4F, 13F, -4F);
        TopBase.setTextureSize(64, 32);
        TopBase.mirror = true;
        setRotation(TopBase, 0F, 0F, 0F);
        TopPole = new ModelRenderer(this, 48, 0);
        TopPole.addBox(0F, 0F, 0F, 4, 3, 4);
        TopPole.setRotationPoint(-2F, 10F, -2F);
        TopPole.setTextureSize(64, 32);
        TopPole.mirror = true;
        setRotation(TopPole, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        ScientificGrinderBase.render(f5);
        TopBase.render(f5);
        TopPole.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
