// Date: 6/23/2014 3:00:47 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package com.labswag.seamusfd.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelScientificGrinder extends ModelBase
{
    //fields
    ModelRenderer ScientificGrinder;
    ModelRenderer Shape2;
    ModelRenderer Shape1;

    public ModelScientificGrinder()
    {
        textureWidth = 64;
        textureHeight = 32;

        ScientificGrinder = new ModelRenderer(this, 0, 0);
        ScientificGrinder.addBox(-8F, 0F, 0F, 16, 15, 14);
        ScientificGrinder.setRotationPoint(0F, 9F, -7F);
        ScientificGrinder.setTextureSize(64, 32);
        ScientificGrinder.mirror = true;
        setRotation(ScientificGrinder, 0F, 0F, 0F);
        Shape2 = new ModelRenderer(this, 0, 0);
        Shape2.addBox(-2F, 0F, 0F, 4, 1, 1);
        Shape2.setRotationPoint(0F, 20F, -8F);
        Shape2.setTextureSize(64, 32);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);
        Shape1 = new ModelRenderer(this, 0, 0);
        Shape1.addBox(0F, 0F, 0F, 4, 4, 1);
        Shape1.setRotationPoint(-2F, 15F, -8F);
        Shape1.setTextureSize(64, 32);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        ScientificGrinder.render(f5);
        Shape1.render(f5);
        Shape1.render(f5);
    }

    public void renderModel(float f)
    {
        ScientificGrinder.render(f);
        Shape1.render(f);
        Shape2.render(f);

    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
